<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Manjunath" failures="1" tests="3" name="Test" time="5.901" errors="0" timestamp="25 Sep 2021 14:20:30 GMT">
  <testcase classname="extentReports_In_Framework_Listeners_Scrnsht.Script" name="updateContact" time="0.018">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at extentReports_In_Framework_Listeners_Scrnsht.Script.updateContact(Script.java:19)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- updateContact -->
  <testcase classname="extentReports_In_Framework_Listeners_Scrnsht.Script" name="createContact" time="0.006"/>
  <testcase classname="extentReports_In_Framework_Listeners_Scrnsht.Script" name="deleteContact" time="0.002"/>
</testsuite> <!-- Test -->
